/*
 * Machine Generated Event String Resource file.
 * NOTE: This file is read only. DO NOT ATTEMPT TO MODIFY IT BY HAND.
 * Generated on 18-December-1998 at 10:21:47
 * Generated from file EVENTS.XLS by MicroProse
 */

char *TheEventStrings[] = {
   "Bullet Damage",
   "Missile Damage",
   "Collision Damage",
   "Bomb Damage",
   "FOD Damage",
   "Damage Type",
   "Damage Amount",
   "Damaged entity's VU_ID",
   "Damaged entity's CampID",
   "Damaged pilot's ID, if any",
   "Damaged entity's description index",
   "Damaged entity's side",
   "Firing entity's VU_ID",
   "Firing entity's CampID",
   "Firing pilot's ID, if any",
   "Firing entity's descripton index",
   "Firing entity's side",
   "Fired weapon's WeaponID",
   "Fired weapon's Unique ID",
   "Gun",
   "Long Range Missile",
   "Medium Range Missile",
   "Short Range Missile",
   "Bomb",
   "Anti-Radiation Missile",
   "Air-Ground Missile",
   "Rocket",
   "Recon Picture",
   "Type of Weapon fired",
   "Firing entity's VU_ID",
   "Firing entity's CampID",
   "Firing pilot's ID, if any",
   "Firing entity's descripton index",
   "Firing entity's side",
   "Fired weapon's WeaponID",
   "Fired weapon's Unique ID",
   "Target entity ID",
   "Shooting entity's ID",
   "Up to 8 weapon Ids",
   "Up to 255 shots each",
   "target's slot, or 255 if none",
   "size of the following block",
   "Current state data",
   "We're about to be attacked",
   "Someone's shooting at us.",
   "Enemy visual detector has spotted us",
   "Enemy radar has spotted us",
   "Repair vehicles or features",
   "Reaggregate this entity",
   "Deaggregate this entity",
   "Who sent this",
   "Message content",
   "Generic Data1",
   "Generic Data2",
   "Generic Data3",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "Who sent this",
   "Message content",
   "Size of data block",
   "The actual data",
   "Detach a number of vehicles",
   "Add Supplies to a unit",
   "New orders",
   "A Mission request was met",
   "Schedule Unit",
   "Schedule Unit",
   "Set number of vehicles",
   "Activate this unit",
   "Fire support orders",
   "",
   "",
   "",
   "Who sent this",
   "Message content",
   "Generic Data1",
   "Generic Data2",
   "Generic Data3",
   "Objective has been capture",
   "Reset this obj's supply traffic",
   "Reset this obj's supply losses",
   "Who sent this",
   "Who it's to",
   "Message",
   "Generic Data1",
   "Generic Data2",
   "Generic Data3",
   "Their orders",
   "Primary Objective",
   "Secondary Objective",
   "Real Objective",
   "Session sending status",
   "size of the following block",
   "The info requested, in a stream",
   "Master's time when posted",
   "Slave's time when received",
   "Slave's time when posted",
   "Who sent this (either way)",
   "Guess at delivery time",
   "Master's time compression",
   "Enemy unit Spotted",
   "Rebuild GTO, ATO, or NTO",
   "Redo planning stage",
   "Entity sending message",
   "Tasker receiving",
   "Team receiving",
   "Message Type",
   "Extra Data1",
   "Extra Data2",
   "Extra Data3 (fake pointer)",
   "New aircraft are available",
   "Player request: aircraft",
   "Player request: mission",
   "Player requested divert",
   "Mission Completed",
   "Mark schedule as used",
   "This airbase has been damaged",
   "Entity sending message",
   "Tasker receiving",
   "Team receiving",
   "Message Type",
   "Extra Data1",
   "Extra Data2",
   "Extra Data3 (fake pointer)",
   "Requesting Artillery/CAS support",
   "Requesting Engineer unit",
   "Requesting Air Defense/CAP",
   "Entity sending message",
   "Tasker receiving",
   "Team receiving",
   "Message Type",
   "Extra Data1",
   "Extra Data2",
   "Enemy being acted against",
   "Requesting Artillery/CAS support",
   "Entity sending message",
   "Tasker receiving",
   "Team receiving",
   "Message Type",
   "Extra Data1",
   "Extra Data2",
   "Enemy being acted against",
   "Relations change",
   "New Team member",
   "Shift inititive values",
   "Entity sending message",
   "Team receiving",
   "Message Type",
   "Acting country",
   "Data1",
   "Data2",
   "Go Spread",
   "Go Wedge",
   "Go Trail",
   "Go Ladder",
   "Go Stack",
   "Go Res Cell",
   "Go Box",
   "Go Arrowhead",
   "Go Fluid Four",
   "Attack My Target",
   "Assign Group",
   "Go Shooter",
   "Go Cover",
   "Weapons Hold",
   "Weapons Free",
   "Break Right",
   "Break Left",
   "Clear My Six",
   "Check Your Six",
   "Pince",
   "Posthole",
   "Chainsaw",
   "Flex",
   "Rejoin",
   "Resume Mission",
   "Search for Ground Targets",
   "Search for Air Targets",
   "Kick Out",
   "Close Up",
   "Toggle Formation Left/Right Side",
   "Step Up",
   "Step Down",
   "Say Position",
   "Say Status",
   "Say Damage",
   "Say Fuel",
   "Weapons Check",
   "Return to Base",
   "Wingman Free",
   "Move up in formation",
   "Radar to Standby",
   "Activate Radar",
   "Buddy Spike",
   "Skate",
   "Run Single-Side Offset",
   "Turn On Smoke",
   "Turn Off Smoke",
   "Raygun",
   "Joker",
   "Bingo",
   "Fumes",
   "Flameout",
   "Total Wingman Messages",
   "Object Sending Message",
   "Unit Receiving Message",
   "Command",
   "New target",
   "A/C Sending Message",
   "New Mode",
   "Team receiving request",
   "The request structure",
   "Data associated with mission",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "Temperature",
   "New wind Heading",
   "New wind Speed",
   "X Offset",
   "Y Offset",
   "How much data we're sendng",
   "Which map edge to add to",
   "Cloud cover or cloud level",
   "Pointer to cloud data",
   "Not finished yet",
   "Kill",
   "Exceeded max time",
   "No Kill",
   "Missed",
   "Exceeded Field Of View",
   "Exceeded Gimbal Limits",
   "Hit the ground",
   "Reached min speed",
   "Exceeded battery life",
   "Dead entity's VU_ID",
   "Damaged entity's CampID",
   "Dead pilot's ID, if any",
   "Dead entity's campaign slot",
   "Dead entity's description index",
   "Dead entity's side",
   "Firing entity's VU_ID",
   "Firing entity's CampID",
   "Firing pilot's ID, if any",
   "Firing entity's campaign slot",
   "Firing entity's descripton index",
   "Firing entity's side",
   "Missile Result",
   "Fired weapon's Unique ID",
   "Wilco",
   "Unable to comply",
   "Judy (AWACS shut up)",
   "Request picture",
   "Request help",
   "Request relief",
   "Request divert mission",
   "Request rescue chopper",
   "Check in",
   "Check out",
   "Vector to home plate",
   "Vector to divert field",
   "Vector to tanker",
   "Vector to package",
   "Vector to nearest threat",
   "Vector to target",
   "Plays PictureBRA call",
   "Campaign ordered a mission abort",
   "Campaign is sending assistance",
   "Flight is at the contact point",
   "Flight's patrol period is over",
   "Flight's patrol has been relieved",
   "Flight ordered to cover another",
   "Flight ordered to intercept enemy",
   "Flight ordered to hit ground veh",
   "Any other type of divert",
   "Requested divert denied",
   "Go back to what you were doing",
   "A flight has taken off",
   "Course correction for intercept",
   "A friendly UNIT is engaged (air or ground)",
   "Declare",
   "A/C making call",
   "Message Type",
   "On Station",
   "Will Comply",
   "Unable to comply",
   "Ready to attack",
   "Notify we're on station",
   "Notify we're off station",
   "Request Mark",
   "Request Target",
   "Request BDA",
   "Request FAC Location",
   "Request FAC Tacan",
   "Hold At CP",
   "FAC Sitrep",
   "Target Marked",
   "Attack Briefing",
   "No Targets Available",
   "Ground Target Bearing",
   "Bomb Damage Assesment",
   "Target Missed",
   "Attacking Friendlies",
   "Can flight re-attack",
   "Target is hardend artillery",
   "Doors Open",
   "Scud Launch Detected",
   "Clear LZ",
   "Attack this target",
   "Send Helos",
   "A/C making call",
   "Message Type",
   "Target Id",
   "Data 1",
   "Data 2",
   "Data 3",
   "Request Landing",
   "Declaring an Emergency",
   "Inbound",
   "Request Takeoff",
   "Request Taxi",
   "tell ATC when you change modes",
   "A/C making call",
   "Message Type",
   "current status of plane",
   "Dead entity's VU_ID",
   "Damaged entity's CampID",
   "Dead pilot's ID, if any",
   "Dead entity's description index",
   "Dead entity's side",
   "Firing entity's VU_ID",
   "Firing entity's CampID",
   "Firing pilot's ID, if any",
   "Firing entity's descripton index",
   "Firing entity's side",
   "Fired weapon's WeaponID",
   "Fired weapon's Unique ID",
   "Campaign units are fighting",
   "Camp Entity has taken losses",
   "A unit is withdrawing or aborted",
   "A unit was destroyed",
   "A new unit has arrived",
   "An objective was captured",
   "A country has switched teams",
   "A triggered event happened",
   "Event Type",
   "Flags",
   "What team this pertains to",
   "Size of string to follow:",
   "Location of this event",
   "",
   "Vu ids of entitys envolved",
   "Text ids of input strings",
   "Who Landed",
   "Landed entity's CampID",
   "Landed pilot's ID",
   "Landed entity's campaign slot",
   "Landed entity's description index",
   "Landing Grade",
   "Lander's strength (0-100%)",
   "Lander's remaining fuel",
   "Owning Entity",
   "Number of Dofs",
   "Number of Switches",
   "Degrees of Freedom",
   "DOF Type",
   "Switch Data",
   "Extra Data",
   "Entity who's data you need",
   "On/Off",
   "",
   "",
   "The game's Id",
   "",
   "",
   "get slot, leave slot, change callsign",
   "Type of game",
   "Team requested",
   "Current slot occupied (if any)",
   "Slot we're asking for",
   "Skill we're asking for",
   "Type we're asking for",
   "Session responding",
   "Sessions game Id",
   "Host's ID",
   "The result of our request",
   "Type of game",
   "Team we got",
   "Slot we got",
   "Pilot slot we got",
   "Pilot skill we got",
   "Who the message is for",
   "Message length",
   "Message",
   "Effect type",
   "Visual id, if needed",
   "",
   "",
   "Location of this effect",
   "",
   "",
   "Velocity of this effect, if needed",
   "",
   "",
   "",
   "The actual data",
   "",
   "",
   "",
   "",
   "",
   "The actual data",
   "",
   "",
   "",
   "",
   "",
   "The actual data",
   "The requesting session",
   "What we still need from the host",
   "Player sending message",
   "Message size",
   "Message buffer (_TCHARs)",
   "Request Fuel",
   "Ready To Take Fuel",
   "Done Refueling",
   "Pumping Fuel",
   "BreakAway",
   "Clear to Pre-contact",
   "Clear to Contact",
   "Stabalize",
   "Boom Command",
   "Disconnect",
   "Tanker entering turn",
   "Position in wait queue",
   "A/C making call",
   "Message Type",
   "Radio Data 1",
   "Radio Data 2",
   "Ejecting plane's VU_ID",
   "Ejecting pilot's VU_ID",
   "Ejecting Camp entity's id",
   "Eject pilot's ID, if any",
   "Ejecting entity's description index",
   "Ejecting entity's side",
   "Ejector's strength (0->100%)",
   "Ejector's remainging fuel",
   "",
   "",
   "",
   "",
   "",
   "",
   "Type of track",
   "VU Id of tracked object",
   "Deaggregation data",
   "",
   "",
   "Status data",
   "Camp Data Message Type",
   "Size of data block",
   "The actual data",
   "Message id",
   "Size of data block",
   "The actual data",
   "Who's saying this",
   "Who this message is for",
   "Voice ID of speaker",
   "# of evals to follow",
   "Eval values",
   "ID of message we're saying",
   "Time to start playing this message",
   "Player Callsign, since this might not be available later",
   "In dogfght… Player team",
   "in Dogfight…Player slot in team",
   "What the player is doing",
   "Object Designating",
   "Object Designated",
   "On or Off",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "",
   "Id of ATC sending message",
   "Command Type",
   "time to land/takeoff",
   "Runway to use",
   "plane to follow",
   "",
   "",
   "",
   "",
   "",
   "number of data link points being sent",
   "classtable index for the target",
   "classtable index for the threat",
   "type of data link point",
   "x coord of data link points",
   "y coord of data link points",
   "z coord of data link points",
   "desired arrival",
   "Who needs data",
   "New position data",
   "",
   "",
   "",
   "Whoever want's yer logbook",
   "The logbook data",
   "Flags used to tell if there is more data",
   "Use this as a type",
   "index into which seg we got",
   "Size of this chunk",
   "overall size",
   "the data block",
   "Size of shit we're sending",
   "The shit.",
   "Size of shit we're sending",
   "The shit.",
   "Size of shit we're sending",
   "The shit.",
   "",
   "",
   "Type of message",
   "The event ID",
   "It's triggered status (on or off)",
   "Session sending status",
   "size of the following block",
   "The info requested, in a stream",
   "Session Sending Message",
   "Type of Message",
   "Value needed to be sent",
   "",
   "",
   "",
   "",
   "",
   "Type of message",
   "size of the following block",
   "Damage Message",
   "Weapon Fire",
   "Campaign Weap Fire",
   "Camp Message",
   "Sim Camp Message",
   "Unit Message",
   "Objective Message",
   "Unit Assignment",
   "Send Campaign data",
   "Timing Message",
   "Camp Tasking Message",
   "Air Tasking Message",
   "Gnd Tasking Message",
   "Naval Tasking Message",
   "Team Message",
   "WingmanMsg",
   "Air AI Mode Change",
   "Mission Request",
   "Divert Message",
   "Wind Change Message",
   "Weather Message",
   "Missile Endgame",
   "AWACSMsg",
   "FAC Message",
   "ATCMsg",
   "Death Message",
   "Campaign Event Message",
   "Landing Message",
   "Control Surface Msg",
   "Sim Data Toggle",
   "Request Dogfight Info",
   "Send Dogfight Info",
   "Request Aircraft Slot",
   "Send aircraft Slot",
   "Graphics Text Display",
   "Add SFX Message",
   "Send Persistant List",
   "Send Objective Data",
   "Send Unit Data",
   "Request Campaign Data",
   "Send Chat Message",
   "TankerMsg",
   "Eject Message",
   "Radar Track Message",
   "Camp Data Message",
   "Voice Data Message",
   "Radio Chatter Message",
   "Player Enter/Exit Sim",
   "Laser Designate Msg",
   "ATC Command",
   "Data Link Message",
   "Request Object",
   "Regeneration Msg",
   "Request Logbook",
   "Send Logbook",
   "Send Image",
   "Flight Plan Message",
   "Sim Dirty Data",
   "Camp Dirty Data",
   "Camp Event Data",
   "Send VC data",
   "Send UI Message",
   "Send Eval Message",
};
