/*
 * Machine Generated String Constants reference file.
 * NOTE: This file is read only. DO NOT ATTEMPT TO MODIFY IT BY HAND.
 * Generated on 18-December-1998 at 10:21:48
 * Generated from file EVENTS.XLS by MicroProse
 */

#ifndef _FALCEVENTRC_H
#define _FALCEVENTRC_H

#define DamageTypeStrIDS0                                   0 
#define DamageTypeStrIDS1                                   1 
#define DamageTypeStrIDS2                                   2 
#define DamageTypeStrIDS3                                   3 
#define DamageTypeStrIDS4                                   4 
#define FalconDamageMessageStrIDS0                          5 
#define FalconDamageMessageStrIDS1                          6 
#define FalconDamageMessageStrIDS2                          7 
#define FalconDamageMessageStrIDS3                          8 
#define FalconDamageMessageStrIDS4                          9 
#define FalconDamageMessageStrIDS5                          10 
#define FalconDamageMessageStrIDS6                          11 
#define FalconDamageMessageStrIDS7                          12 
#define FalconDamageMessageStrIDS8                          13 
#define FalconDamageMessageStrIDS9                          14 
#define FalconDamageMessageStrIDS10                         15 
#define FalconDamageMessageStrIDS11                         16 
#define FalconDamageMessageStrIDS12                         17 
#define FalconDamageMessageStrIDS13                         18 
#define WeaponTypeStrIDS0                                   19 
#define WeaponTypeStrIDS1                                   20 
#define WeaponTypeStrIDS2                                   21 
#define WeaponTypeStrIDS3                                   22 
#define WeaponTypeStrIDS4                                   23 
#define WeaponTypeStrIDS5                                   24 
#define WeaponTypeStrIDS6                                   25 
#define WeaponTypeStrIDS7                                   26 
#define WeaponTypeStrIDS8                                   27 
#define FalconWeaponsFireStrIDS0                            28 
#define FalconWeaponsFireStrIDS1                            29 
#define FalconWeaponsFireStrIDS2                            30 
#define FalconWeaponsFireStrIDS3                            31 
#define FalconWeaponsFireStrIDS4                            32 
#define FalconWeaponsFireStrIDS5                            33 
#define FalconWeaponsFireStrIDS6                            34 
#define FalconWeaponsFireStrIDS7                            35 
#define FalconWeaponsFireStrIDS8                            36 
#define FalconCampWeaponsFireStrIDS0                        37 
#define FalconCampWeaponsFireStrIDS1                        38 
#define FalconCampWeaponsFireStrIDS2                        39 
#define FalconCampWeaponsFireStrIDS3                        40 
#define FalconCampWeaponsFireStrIDS4                        41 
#define FalconCampWeaponsFireStrIDS5                        42 
#define CampMsgTypeStrIDS0                                  43 
#define CampMsgTypeStrIDS1                                  44 
#define CampMsgTypeStrIDS2                                  45 
#define CampMsgTypeStrIDS3                                  46 
#define CampMsgTypeStrIDS4                                  47 
#define CampMsgTypeStrIDS5                                  48 
#define CampMsgTypeStrIDS6                                  49 
#define FalconCampMessageStrIDS0                            50 
#define FalconCampMessageStrIDS1                            51 
#define FalconCampMessageStrIDS2                            52 
#define FalconCampMessageStrIDS3                            53 
#define FalconCampMessageStrIDS4                            54 
#define FalconCampMessageStrIDS5                            55 
#define SimCampMsgTypeStrIDS0                               56 
#define SimCampMsgTypeStrIDS1                               57 
#define SimCampMsgTypeStrIDS2                               58 
#define SimCampMsgTypeStrIDS3                               59 
#define SimCampMsgTypeStrIDS4                               60 
#define SimCampMsgTypeStrIDS5                               61 
#define FalconSimCampMessageStrIDS0                         62 
#define FalconSimCampMessageStrIDS1                         63 
#define FalconSimCampMessageStrIDS2                         64 
#define FalconSimCampMessageStrIDS3                         65 
#define UnitMsgTypeStrIDS0                                  66 
#define UnitMsgTypeStrIDS1                                  67 
#define UnitMsgTypeStrIDS2                                  68 
#define UnitMsgTypeStrIDS3                                  69 
#define UnitMsgTypeStrIDS4                                  70 
#define UnitMsgTypeStrIDS5                                  71 
#define UnitMsgTypeStrIDS6                                  72 
#define UnitMsgTypeStrIDS7                                  73 
#define UnitMsgTypeStrIDS8                                  74 
#define UnitMsgTypeStrIDS9                                  75 
#define UnitMsgTypeStrIDS10                                 76 
#define UnitMsgTypeStrIDS11                                 77 
#define FalconUnitMessageStrIDS0                            78 
#define FalconUnitMessageStrIDS1                            79 
#define FalconUnitMessageStrIDS2                            80 
#define FalconUnitMessageStrIDS3                            81 
#define FalconUnitMessageStrIDS4                            82 
#define ObjMessageStrIDS0                                   83 
#define ObjMessageStrIDS1                                   84 
#define ObjMessageStrIDS2                                   85 
#define FalconObjectiveMessageStrIDS0                       86 
#define FalconObjectiveMessageStrIDS1                       87 
#define FalconObjectiveMessageStrIDS2                       88 
#define FalconObjectiveMessageStrIDS3                       89 
#define FalconObjectiveMessageStrIDS4                       90 
#define FalconObjectiveMessageStrIDS5                       91 
#define FalconUnitAssignmentMessageStrIDS0                  92 
#define FalconUnitAssignmentMessageStrIDS1                  93 
#define FalconUnitAssignmentMessageStrIDS2                  94 
#define FalconUnitAssignmentMessageStrIDS3                  95 
#define FalconSendCampaignStrIDS0                           96 
#define FalconSendCampaignStrIDS1                           97 
#define FalconSendCampaignStrIDS2                           98 
#define FalconTimingMessageStrIDS0                          99 
#define FalconTimingMessageStrIDS1                          100 
#define FalconTimingMessageStrIDS2                          101 
#define FalconTimingMessageStrIDS3                          102 
#define FalconTimingMessageStrIDS4                          103 
#define FalconTimingMessageStrIDS5                          104 
#define CTMMsgTypeStrIDS0                                   105 
#define CTMMsgTypeStrIDS1                                   106 
#define CTMMsgTypeStrIDS2                                   107 
#define FalconCampTaskingMessageStrIDS0                     108 
#define FalconCampTaskingMessageStrIDS1                     109 
#define FalconCampTaskingMessageStrIDS2                     110 
#define FalconCampTaskingMessageStrIDS3                     111 
#define FalconCampTaskingMessageStrIDS4                     112 
#define FalconCampTaskingMessageStrIDS5                     113 
#define FalconCampTaskingMessageStrIDS6                     114 
#define ATMMsgTypeStrIDS0                                   115 
#define ATMMsgTypeStrIDS1                                   116 
#define ATMMsgTypeStrIDS2                                   117 
#define ATMMsgTypeStrIDS3                                   118 
#define ATMMsgTypeStrIDS4                                   119 
#define ATMMsgTypeStrIDS5                                   120 
#define ATMMsgTypeStrIDS6                                   121 
#define FalconAirTaskingMessageStrIDS0                      122 
#define FalconAirTaskingMessageStrIDS1                      123 
#define FalconAirTaskingMessageStrIDS2                      124 
#define FalconAirTaskingMessageStrIDS3                      125 
#define FalconAirTaskingMessageStrIDS4                      126 
#define FalconAirTaskingMessageStrIDS5                      127 
#define FalconAirTaskingMessageStrIDS6                      128 
#define GTMMsgTypeStrIDS0                                   129 
#define GTMMsgTypeStrIDS1                                   130 
#define GTMMsgTypeStrIDS2                                   131 
#define FalconGndTaskingMessageStrIDS0                      132 
#define FalconGndTaskingMessageStrIDS1                      133 
#define FalconGndTaskingMessageStrIDS2                      134 
#define FalconGndTaskingMessageStrIDS3                      135 
#define FalconGndTaskingMessageStrIDS4                      136 
#define FalconGndTaskingMessageStrIDS5                      137 
#define FalconGndTaskingMessageStrIDS6                      138 
#define NTMMsgTypeStrIDS0                                   139 
#define FalconNavalTaskingMessageStrIDS0                    140 
#define FalconNavalTaskingMessageStrIDS1                    141 
#define FalconNavalTaskingMessageStrIDS2                    142 
#define FalconNavalTaskingMessageStrIDS3                    143 
#define FalconNavalTaskingMessageStrIDS4                    144 
#define FalconNavalTaskingMessageStrIDS5                    145 
#define FalconNavalTaskingMessageStrIDS6                    146 
#define TeamMsgTypeStrIDS0                                  147 
#define TeamMsgTypeStrIDS1                                  148 
#define TeamMsgTypeStrIDS2                                  149 
#define FalconTeamMessageStrIDS0                            150 
#define FalconTeamMessageStrIDS1                            151 
#define FalconTeamMessageStrIDS2                            152 
#define FalconTeamMessageStrIDS3                            153 
#define FalconTeamMessageStrIDS4                            154 
#define FalconTeamMessageStrIDS5                            155 
#define WingManCmdStrIDS0                                   156 
#define WingManCmdStrIDS1                                   157 
#define WingManCmdStrIDS2                                   158 
#define WingManCmdStrIDS3                                   159 
#define WingManCmdStrIDS4                                   160 
#define WingManCmdStrIDS5                                   161 
#define WingManCmdStrIDS6                                   162 
#define WingManCmdStrIDS7                                   163 
#define WingManCmdStrIDS8                                   164 
#define WingManCmdStrIDS9                                   165 
#define WingManCmdStrIDS10                                  166 
#define WingManCmdStrIDS11                                  167 
#define WingManCmdStrIDS12                                  168 
#define WingManCmdStrIDS13                                  169 
#define WingManCmdStrIDS14                                  170 
#define WingManCmdStrIDS15                                  171 
#define WingManCmdStrIDS16                                  172 
#define WingManCmdStrIDS17                                  173 
#define WingManCmdStrIDS18                                  174 
#define WingManCmdStrIDS19                                  175 
#define WingManCmdStrIDS20                                  176 
#define WingManCmdStrIDS21                                  177 
#define WingManCmdStrIDS22                                  178 
#define WingManCmdStrIDS23                                  179 
#define WingManCmdStrIDS24                                  180 
#define WingManCmdStrIDS25                                  181 
#define WingManCmdStrIDS26                                  182 
#define WingManCmdStrIDS27                                  183 
#define WingManCmdStrIDS28                                  184 
#define WingManCmdStrIDS29                                  185 
#define WingManCmdStrIDS30                                  186 
#define WingManCmdStrIDS31                                  187 
#define WingManCmdStrIDS32                                  188 
#define WingManCmdStrIDS33                                  189 
#define WingManCmdStrIDS34                                  190 
#define WingManCmdStrIDS35                                  191 
#define WingManCmdStrIDS36                                  192 
#define WingManCmdStrIDS37                                  193 
#define WingManCmdStrIDS38                                  194 
#define WingManCmdStrIDS39                                  195 
#define WingManCmdStrIDS40                                  196 
#define WingManCmdStrIDS41                                  197 
#define WingManCmdStrIDS42                                  198 
#define WingManCmdStrIDS43                                  199 
#define WingManCmdStrIDS44                                  200 
#define WingManCmdStrIDS45                                  201 
#define WingManCmdStrIDS46                                  202 
#define WingManCmdStrIDS47                                  203 
#define WingManCmdStrIDS48                                  204 
#define WingManCmdStrIDS49                                  205 
#define WingManCmdStrIDS50                                  206 
#define WingManCmdStrIDS51                                  207 
#define WingManCmdStrIDS52                                  208 
#define FalconWingmanMsgStrIDS0                             209 
#define FalconWingmanMsgStrIDS1                             210 
#define FalconWingmanMsgStrIDS2                             211 
#define FalconWingmanMsgStrIDS3                             212 
#define AirAIModeMsgStrIDS0                                 213 
#define AirAIModeMsgStrIDS1                                 214 
#define FalconMissionRequestMessageStrIDS0                  215 
#define FalconMissionRequestMessageStrIDS1                  216 
#define FalconDivertMessageStrIDS0                          217 
#define FalconDivertMessageStrIDS1                          218 
#define FalconDivertMessageStrIDS2                          219 
#define FalconDivertMessageStrIDS3                          220 
#define FalconDivertMessageStrIDS4                          221 
#define FalconDivertMessageStrIDS5                          222 
#define FalconDivertMessageStrIDS6                          223 
#define FalconDivertMessageStrIDS7                          224 

#define FalconWeatherMessageStrIDS0							225 
#define FalconWeatherMessageStrIDS1							226 
#define FalconWeatherMessageStrIDS2							227 
#define FalconWeatherMessageStrIDS3							228 
#define FalconWeatherMessageStrIDS4							229 
#define FalconWeatherMessageStrIDS5                         230 
#define FalconWeatherMessageStrIDS6                         231 
#define FalconWeatherMessageStrIDS7                         232 

#define MissileEndCodeStrIDS0                               234 
#define MissileEndCodeStrIDS1                               235 
#define MissileEndCodeStrIDS2                               236 
#define MissileEndCodeStrIDS3                               237 
#define MissileEndCodeStrIDS4                               238 
#define MissileEndCodeStrIDS5                               239 
#define MissileEndCodeStrIDS6                               240 
#define MissileEndCodeStrIDS7                               241 
#define MissileEndCodeStrIDS8                               242 
#define MissileEndCodeStrIDS9                               243 
#define FalconMissileEndMessageStrIDS0                      244 
#define FalconMissileEndMessageStrIDS1                      245 
#define FalconMissileEndMessageStrIDS2                      246 
#define FalconMissileEndMessageStrIDS3                      247 
#define FalconMissileEndMessageStrIDS4                      248 
#define FalconMissileEndMessageStrIDS5                      249 
#define FalconMissileEndMessageStrIDS6                      250 
#define FalconMissileEndMessageStrIDS7                      251 
#define FalconMissileEndMessageStrIDS8                      252 
#define FalconMissileEndMessageStrIDS9                      253 
#define FalconMissileEndMessageStrIDS10                     254 
#define FalconMissileEndMessageStrIDS11                     255 
#define FalconMissileEndMessageStrIDS12                     256 
#define FalconMissileEndMessageStrIDS13                     257 
#define AWACSMsgCodeStrIDS0                                 258 
#define AWACSMsgCodeStrIDS1                                 259 
#define AWACSMsgCodeStrIDS2                                 260 
#define AWACSMsgCodeStrIDS3                                 261 
#define AWACSMsgCodeStrIDS4                                 262 
#define AWACSMsgCodeStrIDS5                                 263 
#define AWACSMsgCodeStrIDS6                                 264 
#define AWACSMsgCodeStrIDS7                                 265 
#define AWACSMsgCodeStrIDS8                                 266 
#define AWACSMsgCodeStrIDS9                                 267 
#define AWACSMsgCodeStrIDS10                                268 
#define AWACSMsgCodeStrIDS11                                269 
#define AWACSMsgCodeStrIDS12                                270 
#define AWACSMsgCodeStrIDS13                                271 
#define AWACSMsgCodeStrIDS14                                272 
#define AWACSMsgCodeStrIDS15                                273 
#define AWACSMsgCodeStrIDS16                                274 
#define AWACSMsgCodeStrIDS17                                275 
#define AWACSMsgCodeStrIDS18                                276 
#define AWACSMsgCodeStrIDS19                                277 
#define AWACSMsgCodeStrIDS20                                278 
#define AWACSMsgCodeStrIDS21                                279 
#define AWACSMsgCodeStrIDS22                                280 
#define AWACSMsgCodeStrIDS23                                281 
#define AWACSMsgCodeStrIDS24                                282 
#define AWACSMsgCodeStrIDS25                                283 
#define AWACSMsgCodeStrIDS26                                284 
#define AWACSMsgCodeStrIDS27                                285 
#define AWACSMsgCodeStrIDS28                                286 
#define AWACSMsgCodeStrIDS29                                287 
#define AWACSMsgCodeStrIDS30                                288 
#define AWACSMsgCodeStrIDS31                                289 
#define FalconAWACSMessageStrIDS0                           290 
#define FalconAWACSMessageStrIDS1                           291 
#define FACMsgCodeStrIDS0                                   292 
#define FACMsgCodeStrIDS1                                   293 
#define FACMsgCodeStrIDS2                                   294 
#define FACMsgCodeStrIDS3                                   295 
#define FACMsgCodeStrIDS4                                   296 
#define FACMsgCodeStrIDS5                                   297 
#define FACMsgCodeStrIDS6                                   298 
#define FACMsgCodeStrIDS7                                   299 
#define FACMsgCodeStrIDS8                                   300 
#define FACMsgCodeStrIDS9                                   301 
#define FACMsgCodeStrIDS10                                  302 
#define FACMsgCodeStrIDS11                                  303 
#define FACMsgCodeStrIDS12                                  304 
#define FACMsgCodeStrIDS13                                  305 
#define FACMsgCodeStrIDS14                                  306 
#define FACMsgCodeStrIDS15                                  307 
#define FACMsgCodeStrIDS16                                  308 
#define FACMsgCodeStrIDS17                                  309 
#define FACMsgCodeStrIDS18                                  310 
#define FACMsgCodeStrIDS19                                  311 
#define FACMsgCodeStrIDS20                                  312 
#define FACMsgCodeStrIDS21                                  313 
#define FACMsgCodeStrIDS22                                  314 
#define FACMsgCodeStrIDS23                                  315 
#define FACMsgCodeStrIDS24                                  316 
#define FACMsgCodeStrIDS25                                  317 
#define FACMsgCodeStrIDS26                                  318 
#define FalconFACMessageStrIDS0                             319 
#define FalconFACMessageStrIDS1                             320 
#define FalconFACMessageStrIDS2                             321 
#define FalconFACMessageStrIDS3                             322 
#define FalconFACMessageStrIDS4                             323 
#define FalconFACMessageStrIDS5                             324 
#define ATCMsgCodeStrIDS0                                   325 
#define ATCMsgCodeStrIDS1                                   326 
#define ATCMsgCodeStrIDS2                                   327 
#define ATCMsgCodeStrIDS3                                   328 
#define ATCMsgCodeStrIDS4                                   329 
#define ATCMsgCodeStrIDS5                                   330 
#define FalconATCMessageStrIDS0                             331 
#define FalconATCMessageStrIDS1                             332 
#define FalconATCMessageStrIDS2                             333 
#define FalconDeathMessageStrIDS0                           334 
#define FalconDeathMessageStrIDS1                           335 
#define FalconDeathMessageStrIDS2                           336 
#define FalconDeathMessageStrIDS3                           337 
#define FalconDeathMessageStrIDS4                           338 
#define FalconDeathMessageStrIDS5                           339 
#define FalconDeathMessageStrIDS6                           340 
#define FalconDeathMessageStrIDS7                           341 
#define FalconDeathMessageStrIDS8                           342 
#define FalconDeathMessageStrIDS9                           343 
#define FalconDeathMessageStrIDS10                          344 
#define FalconDeathMessageStrIDS11                          345 
#define CampEventTypeStrIDS0                                346 
#define CampEventTypeStrIDS1                                347 
#define CampEventTypeStrIDS2                                348 
#define CampEventTypeStrIDS3                                349 
#define CampEventTypeStrIDS4                                350 
#define CampEventTypeStrIDS5                                351 
#define CampEventTypeStrIDS6                                352 
#define CampEventTypeStrIDS7                                353 
#define FalconCampEventMessageStrIDS0                       354 
#define FalconCampEventMessageStrIDS1                       355 
#define FalconCampEventMessageStrIDS2                       356 
#define FalconCampEventMessageStrIDS3                       357 
#define FalconCampEventMessageStrIDS4                       358 
#define FalconCampEventMessageStrIDS5                       359 
#define FalconCampEventMessageStrIDS6                       360 
#define FalconCampEventMessageStrIDS7                       361 
#define FalconLandingMessageStrIDS0                         362 
#define FalconLandingMessageStrIDS1                         363 
#define FalconLandingMessageStrIDS2                         364 
#define FalconLandingMessageStrIDS3                         365 
#define FalconLandingMessageStrIDS4                         366 
#define FalconLandingMessageStrIDS5                         367 
#define FalconLandingMessageStrIDS6                         368 
#define FalconLandingMessageStrIDS7                         369 
#define FalconControlSurfaceMsgStrIDS0                      370 
#define FalconControlSurfaceMsgStrIDS1                      371 
#define FalconControlSurfaceMsgStrIDS2                      372 
#define FalconControlSurfaceMsgStrIDS3                      373 
#define FalconControlSurfaceMsgStrIDS4                      374 
#define FalconControlSurfaceMsgStrIDS5                      375 
#define FalconControlSurfaceMsgStrIDS6                      376 
#define FalconSimDataToggleStrIDS0                          377 
#define FalconSimDataToggleStrIDS1                          378 
#define UI_RequestDogfightInfoStrIDS0                       379 
#define UI_SendDogfightInfoStrIDS0                          380 
#define UI_SendDogfightInfoStrIDS1                          381 
#define UI_SendDogfightInfoStrIDS2                          382 
#define UI_RequestAircraftSlotStrIDS0                       383 
#define UI_RequestAircraftSlotStrIDS1                       384 
#define UI_RequestAircraftSlotStrIDS2                       385 
#define UI_RequestAircraftSlotStrIDS3                       386 
#define UI_RequestAircraftSlotStrIDS4                       387 
#define UI_RequestAircraftSlotStrIDS5                       388 
#define UI_RequestAircraftSlotStrIDS6                       389 
#define UI_RequestAircraftSlotStrIDS7                       390 
#define UI_SendAircraftSlotStrIDS0                          391 
#define UI_SendAircraftSlotStrIDS1                          392 
#define UI_SendAircraftSlotStrIDS2                          393 
#define UI_SendAircraftSlotStrIDS3                          394 
#define UI_SendAircraftSlotStrIDS4                          395 
#define UI_SendAircraftSlotStrIDS5                          396 
#define UI_SendAircraftSlotStrIDS6                          397 
#define UI_SendAircraftSlotStrIDS7                          398 
#define UI_SendAircraftSlotStrIDS8                          399 
#define GraphicsTextDisplayStrIDS0                          400 
#define GraphicsTextDisplayStrIDS1                          401 
#define GraphicsTextDisplayStrIDS2                          402 
#define FalconAddSFXMessageStrIDS0                          403 
#define FalconAddSFXMessageStrIDS1                          404 
#define FalconAddSFXMessageStrIDS2                          405 
#define FalconAddSFXMessageStrIDS3                          406 
#define FalconAddSFXMessageStrIDS4                          407 
#define FalconAddSFXMessageStrIDS5                          408 
#define FalconAddSFXMessageStrIDS6                          409 
#define FalconAddSFXMessageStrIDS7                          410 
#define FalconAddSFXMessageStrIDS8                          411 
#define FalconAddSFXMessageStrIDS9                          412 
#define FalconSendPersistantListStrIDS0                     413 
#define FalconSendPersistantListStrIDS1                     414 
#define FalconSendObjDataStrIDS0                            415 
#define FalconSendObjDataStrIDS1                            416 
#define FalconSendObjDataStrIDS2                            417 
#define FalconSendObjDataStrIDS3                            418 
#define FalconSendObjDataStrIDS4                            419 
#define FalconSendObjDataStrIDS5                            420 
#define FalconSendUnitDataStrIDS0                           421 
#define FalconSendUnitDataStrIDS1                           422 
#define FalconSendUnitDataStrIDS2                           423 
#define FalconSendUnitDataStrIDS3                           424 
#define FalconSendUnitDataStrIDS4                           425 
#define FalconSendUnitDataStrIDS5                           426 
#define FalconRequestCampaignDataStrIDS0                    427 
#define FalconRequestCampaignDataStrIDS1                    428 
#define UI_SendChatMessageStrIDS0                           429 
#define UI_SendChatMessageStrIDS1                           430 
#define UI_SendChatMessageStrIDS2                           431 
#define TankerMsgCodeStrIDS0                                432 
#define TankerMsgCodeStrIDS1                                433 
#define TankerMsgCodeStrIDS2                                434 
#define TankerMsgCodeStrIDS3                                435 
#define TankerMsgCodeStrIDS4                                436 
#define TankerMsgCodeStrIDS5                                437 
#define TankerMsgCodeStrIDS6                                438 
#define TankerMsgCodeStrIDS7                                439 
#define TankerMsgCodeStrIDS8                                440 
#define TankerMsgCodeStrIDS9                                441 
#define TankerMsgCodeStrIDS10                               442 
#define TankerMsgCodeStrIDS11                               443 
#define FalconTankerMessageStrIDS0                          444 
#define FalconTankerMessageStrIDS1                          445 
#define FalconTankerMessageStrIDS2                          446 
#define FalconTankerMessageStrIDS3                          447 
#define FalconEjectMessageStrIDS0                           448 
#define FalconEjectMessageStrIDS1                           449 
#define FalconEjectMessageStrIDS2                           450 
#define FalconEjectMessageStrIDS3                           451 
#define FalconEjectMessageStrIDS4                           452 
#define FalconEjectMessageStrIDS5                           453 
#define FalconEjectMessageStrIDS6                           454 
#define FalconEjectMessageStrIDS7                           455 
#define TrackTypeStrIDS0                                    456 
#define TrackTypeStrIDS1                                    457 
#define TrackTypeStrIDS2                                    458 
#define TrackTypeStrIDS3                                    459 
#define TrackTypeStrIDS4                                    460 
#define TrackTypeStrIDS5                                    461 
#define FalconTrackMessageStrIDS0                           462 
#define FalconTrackMessageStrIDS1                           463 
#define CampDataMsgTypeStrIDS0                              464 
#define CampDataMsgTypeStrIDS1                              465 
#define CampDataMsgTypeStrIDS2                              466 
#define CampDataMsgTypeStrIDS3                              467 
#define FalconCampDataMessageStrIDS0                        468 
#define FalconCampDataMessageStrIDS1                        469 
#define FalconCampDataMessageStrIDS2                        470 
#define FalconVoiceDataMessageStrIDS0                       471 
#define FalconVoiceDataMessageStrIDS1                       472 
#define FalconVoiceDataMessageStrIDS2                       473 
#define FalconRadioChatterMessageStrIDS0                    474 
#define FalconRadioChatterMessageStrIDS1                    475 
#define FalconRadioChatterMessageStrIDS2                    476 
#define FalconRadioChatterMessageStrIDS3                    477 
#define FalconRadioChatterMessageStrIDS4                    478 
#define FalconRadioChatterMessageStrIDS5                    479 
#define FalconRadioChatterMessageStrIDS6                    480 
#define FalconPlayerStatusMessageStrIDS0                    481 
#define FalconPlayerStatusMessageStrIDS1                    482 
#define FalconPlayerStatusMessageStrIDS2                    483 
#define FalconPlayerStatusMessageStrIDS3                    484 
#define FalconLaserDesignateMsgStrIDS0                      485 
#define FalconLaserDesignateMsgStrIDS1                      486 
#define FalconLaserDesignateMsgStrIDS2                      487 
#define ATCCmdCodeStrIDS0                                   488 
#define ATCCmdCodeStrIDS1                                   489 
#define ATCCmdCodeStrIDS2                                   490 
#define ATCCmdCodeStrIDS3                                   491 
#define ATCCmdCodeStrIDS4                                   492 
#define ATCCmdCodeStrIDS5                                   493 
#define ATCCmdCodeStrIDS6                                   494 
#define ATCCmdCodeStrIDS7                                   495 
#define ATCCmdCodeStrIDS8                                   496 
#define ATCCmdCodeStrIDS9                                   497 
#define ATCCmdCodeStrIDS10                                  498 
#define ATCCmdCodeStrIDS11                                  499 
#define ATCCmdCodeStrIDS12                                  500 
#define ATCCmdCodeStrIDS13                                  501 
#define ATCCmdCodeStrIDS14                                  502 
#define ATCCmdCodeStrIDS15                                  503 
#define ATCCmdCodeStrIDS16                                  504 
#define ATCCmdCodeStrIDS17                                  505 
#define ATCCmdCodeStrIDS18                                  506 
#define ATCCmdCodeStrIDS19                                  507 
#define ATCCmdCodeStrIDS20                                  508 
#define ATCCmdCodeStrIDS21                                  509 
#define ATCCmdCodeStrIDS22                                  510 
#define ATCCmdCodeStrIDS23                                  511 
#define FalconATCCmdMessageStrIDS0                          512 
#define FalconATCCmdMessageStrIDS1                          513 
#define FalconATCCmdMessageStrIDS2                          514 
#define FalconATCCmdMessageStrIDS3                          515 
#define FalconATCCmdMessageStrIDS4                          516 
#define DLinkPointTypeStrIDS0                               517 
#define DLinkPointTypeStrIDS1                               518 
#define DLinkPointTypeStrIDS2                               519 
#define DLinkPointTypeStrIDS3                               520 
#define DLinkPointTypeStrIDS4                               521 
#define FalconDLinkMessageStrIDS0                           522 
#define FalconDLinkMessageStrIDS1                           523 
#define FalconDLinkMessageStrIDS2                           524 
#define FalconDLinkMessageStrIDS3                           525 
#define FalconDLinkMessageStrIDS4                           526 
#define FalconDLinkMessageStrIDS5                           527 
#define FalconDLinkMessageStrIDS6                           528 
#define FalconDLinkMessageStrIDS7                           529 
#define FalconRequestObjectStrIDS0                          530 
#define FalconRegenerationMessageStrIDS0                    531 
#define FalconRegenerationMessageStrIDS1                    532 
#define FalconRegenerationMessageStrIDS2                    533 
#define FalconRegenerationMessageStrIDS3                    534 
#define UI_RequestLogbookStrIDS0                            535 
#define UI_SendLogbookStrIDS0                               536 
#define UI_SendLogbookStrIDS1                               537 
#define UI_SendImageStrIDS0                                 538 
#define UI_SendImageStrIDS1                                 539 
#define UI_SendImageStrIDS2                                 540 
#define UI_SendImageStrIDS3                                 541 
#define UI_SendImageStrIDS4                                 542 
#define FalconFlightPlanMessageStrIDS0                      543 
#define FalconFlightPlanMessageStrIDS1                      544 
#define SimDirtyDataStrIDS0                                 545 
#define SimDirtyDataStrIDS1                                 546 
#define CampDirtyDataStrIDS0                                547 
#define CampDirtyDataStrIDS1                                548 
#define eventMsgTypeStrIDS0                                 549 
#define eventMsgTypeStrIDS1                                 550 
#define CampEventDataMessageStrIDS0                         551 
#define CampEventDataMessageStrIDS1                         552 
#define CampEventDataMessageStrIDS2                         553 
#define FalconSendVCStrIDS0                                 554 
#define FalconSendVCStrIDS1                                 555 
#define FalconSendVCStrIDS2                                 556 
#define UISendMsgStrIDS0                                    557 
#define UISendMsgStrIDS1                                    558 
#define UISendMsgStrIDS2                                    559 
#define evalMsgTypeStrIDS0                                  560 
#define evalMsgTypeStrIDS1                                  561 
#define evalMsgTypeStrIDS2                                  562 
#define evalMsgTypeStrIDS3                                  563 
#define evalMsgTypeStrIDS4                                  564 
#define SendEvalMessageStrIDS0                              565 
#define SendEvalMessageStrIDS1                              566 
#define FalconMsgStrIDS0                                    567 
#define FalconMsgStrIDS1                                    568 
#define FalconMsgStrIDS2                                    569 
#define FalconMsgStrIDS3                                    570 
#define FalconMsgStrIDS4                                    571 
#define FalconMsgStrIDS5                                    572 
#define FalconMsgStrIDS6                                    573 
#define FalconMsgStrIDS7                                    574 
#define FalconMsgStrIDS8                                    575 
#define FalconMsgStrIDS9                                    576 
#define FalconMsgStrIDS10                                   577 
#define FalconMsgStrIDS11                                   578 
#define FalconMsgStrIDS12                                   579 
#define FalconMsgStrIDS13                                   580 
#define FalconMsgStrIDS14                                   581 
#define FalconMsgStrIDS15                                   582 
#define FalconMsgStrIDS16                                   583 
#define FalconMsgStrIDS17                                   584 
#define FalconMsgStrIDS18                                   585 
#define FalconMsgStrIDS19                                   586 
#define FalconMsgStrIDS20                                   587 
#define FalconMsgStrIDS21                                   588 
#define FalconMsgStrIDS22                                   589 
#define FalconMsgStrIDS23                                   590 
#define FalconMsgStrIDS24                                   591 
#define FalconMsgStrIDS25                                   592 
#define FalconMsgStrIDS26                                   593 
#define FalconMsgStrIDS27                                   594 
#define FalconMsgStrIDS28                                   595 
#define FalconMsgStrIDS29                                   596 
#define FalconMsgStrIDS30                                   597 
#define FalconMsgStrIDS31                                   598 
#define FalconMsgStrIDS32                                   599 
#define FalconMsgStrIDS33                                   600 
#define FalconMsgStrIDS34                                   601 
#define FalconMsgStrIDS35                                   602 
#define FalconMsgStrIDS36                                   603 
#define FalconMsgStrIDS37                                   604 
#define FalconMsgStrIDS38                                   605 
#define FalconMsgStrIDS39                                   606 
#define FalconMsgStrIDS40                                   607 
#define FalconMsgStrIDS41                                   608 
#define FalconMsgStrIDS42                                   609 
#define FalconMsgStrIDS43                                   610 
#define FalconMsgStrIDS44                                   611 
#define FalconMsgStrIDS45                                   612 
#define FalconMsgStrIDS46                                   613 
#define FalconMsgStrIDS47                                   614 
#define FalconMsgStrIDS48                                   615 
#define FalconMsgStrIDS49                                   616 
#define FalconMsgStrIDS50                                   617 
#define FalconMsgStrIDS51                                   618 
#define FalconMsgStrIDS52                                   619 
#define FalconMsgStrIDS53                                   620 
#define FalconMsgStrIDS54                                   621 
#define FalconMsgStrIDS55                                   622 
#define FalconMsgStrIDS56                                   623 
#define FalconMsgStrIDS57                                   624 
#define FalconMsgStrIDS58                                   625 
#define FalconMsgStrIDS59                                   626 
#define FalconMsgStrIDS60                                   627 
#define FalconMsgStrIDS61                                   628 
#define FalconMsgStrIDS62                                   629 
#endif

