
/********************************************************************/
/*  Copyright (C) 1997 Spectrum HoloByte, Inc. All rights reserved  */
/*                                                                  */
/*  Programs, statements and coded instructions within this         */
/*  file contain unpublished and proprietary information of         */
/*  Spectrum HoloByte, Inc. and are thus protected by the Federal   */
/*  Copyright law.  They may not be copied, duplicated or disclosed */
/*  to third parties in any form, in whole or in part, without the  */
/*  prior written consent of Spectrum HoloByte, Inc.                */
/*                                                                  */
/********************************************************************/

/*
  This cludge 'enumerates' the various valid TARGETs so we
  may use them for #if tests with the BUILDING_FOR_* macros.
  (SEE: shi.h)
 
     ** THIS FILE IS AUTOMATICALLY GENERATED **
*/
 
 
#ifndef _SHI__TARGETS_H_
#define _SHI__TARGETS_H_
 
#define SHI_CS_m_68k	4
#define SHI_CS_m_i486	5
#define SHI_CS_m_i586	6
#define SHI_CS_m_i686	7
#define SHI_CS_m_i786	8
#define SHI_CS_m_i886	9
#define SHI_CS_m_k6_2   10
#define SHI_CS_m_m2	11
#define SHI_CS_m_mips1	12
#define SHI_CS_m_mips2	13
#define SHI_CS_m_mips3	14
#define SHI_CS_m_ppc601	15
#define SHI_CS_m_psx	16
#define SHI_CS_m_saturn	17
#define SHI_CS_m_u64	18
 
#endif  /* _SHI__TARGETS_H_ */
