#ifndef _UI_EVENTS_H_
#define _UI_EVENTS_H_

/*

enum
{
	EID_GUN_USED          =1,
	EID_MISSILE_USED      =2,
	EID_BOMB_USED         =3,
	EID_ROCKET_USED       =4,
	EID_DEATH             =5,
	EID_WEAPON_DAMAGE     =6,
	EID_MID_AIR_DAMAGE    =7,
	EID_HIT_GROUND_DAMAGE =8,
	EID_HIT_BLDNG_DAMAGE  =9,
	EID_PROXIMITY_DAMAGE  =10,
	EID_DEBRIS_DAMAGE     =11,
	EID_MISSILE_DONE      =12,
	EID_LANDING           =13,
	EID_CALLSIGN_EJECT    =14,
	EID_PLANE_EJECT       =15,
	EID_PLAYER_ENTER_SIM  =16,
	EID_PLAYER_LEFT_SIM   =17,
	EID_NUM_STRINGS,
};

enum
{
	EVT_MSG_DISCARD           = 0,
	EVT_MSG_GUN_USED          = EID_GUN_USED,
	EVT_MSG_MISSILE_USED      = EID_MISSILE_USED,
	EVT_MSG_BOMB_USED         = EID_BOMB_USED,
	EVT_MSG_ROCKET_USED       = EID_ROCKET_USED,
	EVT_MSG_DEATH             = EID_DEATH,
	EVT_MSG_WEAPON_DMG        = EID_WEAPON_DAMAGE,
	EVT_MSG_MID_AIR_DMG       = EID_MID_AIR_DAMAGE,
	EVT_MSG_HIT_GROUND_DMG    = EID_HIT_GROUND_DAMAGE,
	EVT_MSG_HIT_BUILDING_DMG  = EID_HIT_BLDNG_DAMAGE,
	EVT_MSG_EXPLOSION_DMG     = EID_PROXIMITY_DAMAGE,
	EVT_MSG_HIT_DEBRIS_DMG    = EID_DEBRIS_DAMAGE,
	EVT_MSG_MISSILE_DONE      = EID_MISSILE_DONE,
	EVT_MSG_LANDING           = EID_LANDING,
	EVT_MSG_PLAYER_EJECT      = EID_CALLSIGN_EJECT,
	EVT_MSG_PLANE_EJECT       = EID_PLANE_EJECT,
	EVT_MSG_ENTER_SIM         = EID_PLAYER_ENTER_SIM,
	EVT_MSG_LEAVE_SIM         = EID_PLAYER_LEFT_SIM,
};

typedef struct
{
	_TCHAR ParamStr[80];
	short  Count;
	short  Order[EVT_MAX_PARAMS];
} DEBRIEF_EVENT;
*/

#endif