// ffshaderblobs.cpp -- Artscout - 2026: the generated bytecode headers, wrapped
// in one lookup. Regenerated by tools/build_shaders before every compile, so a
// stale blob cannot survive a shader edit.
#include "ffshaderblobs.h"

// DXIL is Windows-only (no D3D12 elsewhere); SPIR-V is built on both.
#ifdef _WIN32
#include "generated/g_ffterrain_as_dxil.h"
#include "generated/g_ffterrain_ms_dxil.h"
#include "generated/g_ffterrain_ps_dxil.h"
#endif

#include "generated/g_ffterrain_as_spv.h"
#include "generated/g_ffterrain_ms_spv.h"
#include "generated/g_ffterrain_ps_spv.h"

#include "generated/g_ffobject_vs_spv.h"
#include "generated/g_ffobject_ps_spv.h"
#include "generated/g_ffscreen_vs_spv.h"
#include "generated/g_ffscreen_ps_spv.h"
#include "generated/g_ffparticle_vs_spv.h"
#include "generated/g_ffparticle_ps_spv.h"
#include "generated/g_ffcomposite_vs_spv.h"
#include "generated/g_ffcomposite_ps_spv.h"
#include "generated/g_ffxrblit_vs_spv.h"
#include "generated/g_ffxrblit_ps_spv.h"

namespace
{
struct BlobEntry
{
    const void* dxil;
    unsigned int dxilSize;
    const void* spirv;
    unsigned int spirvSize;
    const char* name;
};

#ifdef _WIN32
#define FF_DXIL(v) (const void*)v, (unsigned int)sizeof(v)
#else
#define FF_DXIL(v) (const void*)0, 0u
#endif

const BlobEntry s_blobs[FFSHADER_COUNT] = {
    {FF_DXIL(g_ffterrain_as_dxil), (const void*)g_ffterrain_as_spv,
     (unsigned int)sizeof(g_ffterrain_as_spv), "ffterrain.AS_Terrain"},
    {FF_DXIL(g_ffterrain_ms_dxil), (const void*)g_ffterrain_ms_spv,
     (unsigned int)sizeof(g_ffterrain_ms_spv), "ffterrain.MS_Terrain"},
    {FF_DXIL(g_ffterrain_ps_dxil), (const void*)g_ffterrain_ps_spv,
     (unsigned int)sizeof(g_ffterrain_ps_spv), "ffterrain.PS_Terrain"},

    // SPIR-V only: the D3D12 side of these passes lives in ffemu.hlsl.
#define FF_SPV_ONLY(v, name)                                                   \
    {                                                                          \
        (const void*)0, 0u, (const void*)v, (unsigned int)sizeof(v), name      \
    }
    FF_SPV_ONLY(g_ffobject_vs_spv, "ffobject.VS_Object"),
    FF_SPV_ONLY(g_ffobject_ps_spv, "ffobject.PS_Object"),
    FF_SPV_ONLY(g_ffscreen_vs_spv, "ffscreen.VS_Screen"),
    FF_SPV_ONLY(g_ffscreen_ps_spv, "ffscreen.PS_Screen"),
    FF_SPV_ONLY(g_ffparticle_vs_spv, "ffparticle.VS_Particle"),
    FF_SPV_ONLY(g_ffparticle_ps_spv, "ffparticle.PS_Particle"),
    FF_SPV_ONLY(g_ffcomposite_vs_spv, "ffcomposite.VS_Composite"),
    FF_SPV_ONLY(g_ffcomposite_ps_spv, "ffcomposite.PS_Composite"),
    FF_SPV_ONLY(g_ffxrblit_vs_spv, "ffxrblit.VS_XrBlit"),
    FF_SPV_ONLY(g_ffxrblit_ps_spv, "ffxrblit.PS_XrBlit"),
#undef FF_SPV_ONLY
};

#undef FF_DXIL
} // namespace

const void* FFGetShaderBlob(FFShaderId id, FFShaderTarget target,
                            unsigned int* sizeBytes)
{
    if (sizeBytes)
        *sizeBytes = 0;
    if (id < 0 || id >= FFSHADER_COUNT)
        return 0;

    const BlobEntry& e = s_blobs[id];
    const void* p = (target == FFSHADER_DXIL) ? e.dxil : e.spirv;
    const unsigned int n = (target == FFSHADER_DXIL) ? e.dxilSize : e.spirvSize;

    if (!p || !n)
        return 0;
    if (sizeBytes)
        *sizeBytes = n;
    return p;
}

const char* FFGetShaderName(FFShaderId id)
{
    if (id < 0 || id >= FFSHADER_COUNT)
        return "?";
    return s_blobs[id].name;
}
